/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ems;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Nuwan
 */
public class ad_home extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
 String url="jdbc:mysql://localhost:3306/project?zeroDateTimeBehavior=convertToNull";
    Statement st=null;
    /**
     * Creates new form ad_home
     */
    public ad_home() {
        initComponents();
    }
private void setaid(){
    viewad_man vw = new viewad_man();
    viewad_man.lblid.setText(this.txtadsr.getText());
    vw.setVisible(true);
    this.dispose();
    
    
    
}private void srch(){
    String sch=txtadsr.getText();
    if(sch.isEmpty())
    {
    JOptionPane.showMessageDialog(null,"Please Enter EMP ID","Erorr",JOptionPane.ERROR_MESSAGE);
    }
    else{
    setaid();
    
    }
    
    }


private void edit(){
    editg edt = new editg();
    editg.txtedtgid.setText(ad_home.txtadsr.getText());
    edt.setVisible(true);
    this.dispose();
}
private void editmsg(){
    String sch=txtadsr.getText();
    if(sch.isEmpty())
    {
    JOptionPane.showMessageDialog(null,"Please Enter EMP ID","Erorr",JOptionPane.ERROR_MESSAGE);
    }
    else{
    edit();
    
    }
    
}

  private void delete(){
        
          String del=txtadsr.getText();
         String gqry,aqry="";
          try{
              Connection conn = DriverManager.getConnection(url,"root","");
               System.out.println("Connection Successfully");
               aqry="DELETE FROM `project`.`emp_advance` WHERE `emp_advance`.`emp_id` = ('"+del+"')";
                gqry="DELETE FROM `project`.`genaral` WHERE `genaral`.`id` = ('"+del+"')";
               st=conn.createStatement();
      JOptionPane.showMessageDialog(null,"Delete complete.....!");
      st.executeUpdate(aqry);
      st.executeUpdate(gqry);
      st.close();
          }
          
          catch(SQLException | HeadlessException e){
        System.out.println("Connection Faild.........!"+e);
        JOptionPane.showMessageDialog(null,"Connection Faild"+e,"Erorr",JOptionPane.ERROR_MESSAGE);
       
        
    }
    }
  private void dlttmsg_yes_no(){
int dailogButton = JOptionPane.YES_NO_OPTION;
int dailogResult = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete this data...?","Delete ",dailogButton);
if(dailogResult==0){
    delete();
    System.out.println("Yes option");
}
else{
    System.out.println("No Option");
}    
  }
  private void dlttmsg(){
    String sch=txtadsr.getText();
    if(sch.isEmpty())
    {
    JOptionPane.showMessageDialog(null,"Please Enter EMP ID","Erorr",JOptionPane.ERROR_MESSAGE);
    }
    else{
    dlttmsg_yes_no();
    
    }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnaddnew = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtadsr = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        btnbook = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(940, 570));
        jPanel1.setLayout(null);

        btnaddnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/addnew_1.png"))); // NOI18N
        btnaddnew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaddnew.setPreferredSize(new java.awt.Dimension(122, 95));
        btnaddnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnewActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddnew);
        btnaddnew.setBounds(360, 420, 122, 95);

        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/edit.png"))); // NOI18N
        btnedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnedit.setPreferredSize(new java.awt.Dimension(122, 95));
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit);
        btnedit.setBounds(70, 270, 80, 95);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/delete.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(180, 270, 120, 90);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/mangerbtn.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(500, 410, 150, 120);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/settings.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton4);
        jButton4.setBounds(700, 410, 110, 120);

        txtadsr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtadsr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtadsr);
        txtadsr.setBounds(80, 150, 160, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/serch.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setPreferredSize(new java.awt.Dimension(169, 157));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(320, 140, 169, 157);

        btnbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/book.png"))); // NOI18N
        btnbook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbook.setPreferredSize(new java.awt.Dimension(160, 160));
        btnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookActionPerformed(evt);
            }
        });
        jPanel1.add(btnbook);
        btnbook.setBounds(670, 50, 160, 160);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter EMP ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 190, 100, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/home.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dlttmsg();



// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnaddnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnewActionPerformed

this.dispose();
new add_frm().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnaddnewActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

new manager_signup().setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookActionPerformed

new tbl().setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_btnbookActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
srch();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed

editmsg();    
// TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                 
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ad_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ad_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ad_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ad_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ad_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddnew;
    private javax.swing.JButton btnbook;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtadsr;
    // End of variables declaration//GEN-END:variables
}
