/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ems;

import java.awt.event.WindowEvent;
import java.sql.*;
import java.awt.*;
import javax.swing.JOptionPane;
import java.io.*;
import java.io.File;





public class adminreg extends javax.swing.JFrame {

    
    
    String url="jdbc:mysql://localhost:3306/project?zeroDateTimeBehavior=convertToNull";
    Statement st=null;
   
    
    
    
    
    public adminreg() {
        initComponents();
    }
    
    public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    
private void WWRite(){
        try{ 
            File myFile = new File("text.txt");
            myFile.createNewFile();
            try (FileWriter write = new FileWriter(myFile)) {
                write.write("1");
                write.flush();
            }
           
        }catch(Exception e){
            
            
            }
              
       
        
    }

    @SuppressWarnings("deprecation")
    private void msgbox(){
    
    String name=txtnm.getText();
    String nic=txtnic.getText();
    @SuppressWarnings("deprecation")
    String ps=txtps.getText();
    String us=txtus.getText();
    @SuppressWarnings("deprecation")
    String rps;
        rps = txtrps.getText();
    
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please Enter Your Name","Erorr",JOptionPane.ERROR_MESSAGE);
        }
        else if(nic.isEmpty())
        {
        JOptionPane.showMessageDialog(null,"Please Enter Your NIC","Erorr",JOptionPane.ERROR_MESSAGE);     
        }
        else if(us.isEmpty())
        {
        JOptionPane.showMessageDialog(null,"Your User Name Empty","Erorr",JOptionPane.ERROR_MESSAGE);     
        }
        else if(ps.isEmpty())
        {
        JOptionPane.showMessageDialog(null,"Your Password Empty","Erorr",JOptionPane.ERROR_MESSAGE);     
        }
        else if(rps.isEmpty())
        {
        JOptionPane.showMessageDialog(null,"Please verify Your Passward","Erorr",JOptionPane.ERROR_MESSAGE);    
        
        }
       
        else if(  ps == null ? rps == null : ps.equals(rps))
   {
    JOptionPane.showMessageDialog(null,"Your password verify...!");
            WWRite();
            connect();
            this.dispose();
            new ad_home().setVisible(true);
   
   }
    else
            
        {
        JOptionPane.showMessageDialog(null,"Password verify Failed....","Erorr",JOptionPane.ERROR_MESSAGE);    
       
        }
}

    @SuppressWarnings("deprecation")
    private void connect(){

String nm,nic,ps,us,qry="";

nm=txtnm.getText();
nic=txtnic.getText();
ps=txtps.getText();
us=txtus.getText();

try{
Connection conn=DriverManager.getConnection(url,"root","");
System.out.println("Connection Successfully");
 qry="INSERT INTO `project`.`admin` (`name`, `nic`, `user_name`, `password`) VALUES ('"+nm+"', '"+nic+"', '"+us+"', '"+ps+"')";
st=conn.createStatement();
 JOptionPane.showMessageDialog(null,nm+" Your Account Create Successfully");
 st.executeUpdate(qry);
 st.close();
}

    catch(SQLException | HeadlessException e){
        System.out.println("Connection Faild.........!"+e);
        JOptionPane.showMessageDialog(null,"Connection Faild"+e,"Erorr",JOptionPane.ERROR_MESSAGE);
       
    
    } 
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnadmin = new javax.swing.JButton();
        txtrps = new javax.swing.JPasswordField();
        txtps = new javax.swing.JPasswordField();
        txtus = new javax.swing.JTextField();
        txtnic = new javax.swing.JTextField();
        txtnm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        btnadmin.setBackground(new java.awt.Color(102, 153, 255));
        btnadmin.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        btnadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/signup.png"))); // NOI18N
        btnadmin.setPreferredSize(new java.awt.Dimension(125, 35));
        btnadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminActionPerformed(evt);
            }
        });
        jPanel1.add(btnadmin);
        btnadmin.setBounds(140, 340, 125, 35);
        jPanel1.add(txtrps);
        txtrps.setBounds(200, 260, 170, 30);
        jPanel1.add(txtps);
        txtps.setBounds(200, 210, 170, 30);

        txtus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusActionPerformed(evt);
            }
        });
        jPanel1.add(txtus);
        txtus.setBounds(200, 170, 170, 30);

        txtnic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtnic);
        txtnic.setBounds(200, 130, 170, 30);

        txtnm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnmKeyPressed(evt);
            }
        });
        jPanel1.add(txtnm);
        txtnm.setBounds(200, 90, 170, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Verify Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 260, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 220, 70, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("User Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 180, 90, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Your NIC Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 140, 140, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Your Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 100, 90, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Administrator Sign Up");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 20, 210, 22);

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/cn.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 340, 125, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/sign up admn.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, -10, 480, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void txtusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminActionPerformed
      
msgbox();
    
    
       
    }//GEN-LAST:event_btnadminActionPerformed

    private void txtnmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnmKeyPressed
        

    }//GEN-LAST:event_txtnmKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();


    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                
                
                new adminreg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtnm;
    private javax.swing.JPasswordField txtps;
    private javax.swing.JPasswordField txtrps;
    private javax.swing.JTextField txtus;
    // End of variables declaration//GEN-END:variables
}
