/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ems;

//import javax.swing.JFrame;
import java.io.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Nuwan
 */
public class admin extends javax.swing.JFrame {

 Statement st=null;
     
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @return 
     */
   
      public static Connection Connectdb(){
    
    try{
     Class.forName("com.mysql.jdbc.Driver");
     Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?zeroDateTimeBehavior=convertToNull","root","");
     
     return conn;
     
    }catch(ClassNotFoundException | SQLException e){
         JOptionPane.showMessageDialog(null,"Connection Faild"+e,"Erorr",JOptionPane.ERROR_MESSAGE);  
     return null;
     
        
    }
    
}    
 @SuppressWarnings("deprecation")
 private void lgn() throws SQLException{
     String qry="select user_name,password from genaral where user_name=? and password=?;";
     int loginAttemps;
     try{
         pst=conn.prepareStatement(qry);
         pst.setString(1,txtuser.getText());
         pst.setString(2,txtps.getText());
         rs=pst.executeQuery();
         if(rs.next())
         
         {
             JOptionPane.showMessageDialog(null,"Username & Password Correct");
 
             this.dispose();
              new emphome().setVisible(true);
              rs.close();
         
         
         }
         
         
              else
             
                     
         {
             
 JOptionPane.showMessageDialog(null,"Username & Password Invalid","Erorr",JOptionPane.ERROR_MESSAGE);
 
         }
         
         
     }
       catch(SQLException | HeadlessException e){
        
        JOptionPane.showMessageDialog(null,"Faild"+e,"Erorr",JOptionPane.ERROR_MESSAGE);    
     }
     
 } 
       
      
 
     
    public void close(){
        WindowEvent winclosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosingEvent);
        
    }
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtps = new javax.swing.JPasswordField();
        btnemplogin = new javax.swing.JToggleButton();
        btncancel = new javax.swing.JButton();
        jblimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(420, 515));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/login admin.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(350, 60));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 80, 350, 60);

        jButton2.setBackground(new java.awt.Color(51, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/login manager.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 170, 350, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("User Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 340, 80, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Let's Get Started for Employee");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 280, 280, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 380, 60, 15);

        txtuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtuser);
        txtuser.setBounds(150, 340, 180, 25);

        txtps.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtps);
        txtps.setBounds(150, 380, 180, 25);

        btnemplogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/login.png"))); // NOI18N
        btnemplogin.setPreferredSize(new java.awt.Dimension(125, 35));
        btnemplogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemploginActionPerformed(evt);
            }
        });
        jPanel1.add(btnemplogin);
        btnemplogin.setBounds(70, 460, 125, 35);

        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/cn.png"))); // NOI18N
        btncancel.setPreferredSize(new java.awt.Dimension(125, 35));
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel);
        btncancel.setBounds(250, 460, 125, 35);

        jblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/lgnfrm.png"))); // NOI18N
        jPanel1.add(jblimage);
        jblimage.setBounds(0, 0, 420, 515);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

 
 admnregester a=new admnregester();
 a.setVisible(true);
 this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

manegerregister m=new manegerregister();
m.setVisible(true);
this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        conn=Connectdb();
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnemploginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemploginActionPerformed

     try {        
         lgn();
// TODO add your handling code here:
     } catch (SQLException ex) {
         Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_btnemploginActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
this.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                } else {
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                String file="text.txt";
                
                  try
                {
                    Thread.sleep(4500);
                }     
                   catch(Exception e)
                   {
                       
                   }
               try{
                    
                    FileReader myFile = new FileReader(file);
                    try (BufferedReader buffer = new BufferedReader(myFile)) {
                        String line;
                        
                        
                        while((line=buffer.readLine())!=null){
                            
                            System.out.print(line);
                            int value=Integer.parseInt(line);
                            if(value==0){
                                new adminreg().setVisible(true);
                                
                            }else{
                                new admin().setVisible(true);
                                
                            }
                            
                            
                            
                            
                        }
                    }
                }catch(IOException | NumberFormatException e){
                    System.out.println(e);
                }
                  
                  
                  
                //new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JToggleButton btnemplogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblimage;
    private javax.swing.JPasswordField txtps;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
